"""Typed configuration objects for preprocessing module."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

from config.constants import DEAP_ROOT

if TYPE_CHECKING:
    from config.option_utils import PreprocessingMethod

__all__ = ["PreprocessingOption"]


@dataclass(slots=True)
class PreprocessingOption:
    """Container describing a specific preprocessing configuration."""

    name: str
    root_dir: str | Path
    preprocessing_method: PreprocessingMethod
    root_path: Path = field(init=False)

    def __post_init__(self) -> None:
        root_dir_path = Path(self.root_dir)
        self.root_path = DEAP_ROOT / "generated" / root_dir_path
        self.root_path.mkdir(parents=True, exist_ok=True)

    def get_subject_path(self) -> Path:
        """Directory for subject-level numpy arrays."""
        path = self.root_path / "subject"
        return path

    def get_subject_metadata_path(self) -> Path:
        """Directory for metadata produced during subject preprocessing."""
        return self.get_subject_path() / "metadata"

    def get_subject_metadata_params_path(self) -> Path:
        """Path to the parameters JSON metadata file for subject preprocessing."""
        return self.get_subject_metadata_path() / "params.json"

    def get_subject_metadata_metrics_path(self) -> Path:
        """Path to the metrics JSON metadata file for subject preprocessing."""
        return self.get_subject_metadata_path() / "metrics.json"

    def get_subject_metadata_shape_path(self) -> Path:
        """Path to the shape CSV metadata file for subject preprocessing."""
        return self.get_subject_metadata_path() / "shape.csv"

    def get_trial_path(self) -> Path:
        """Directory for per-trial joblib data frames produced by splitting."""
        path = self.root_path / "trial"
        return path

    def get_metadata_path(self) -> Path:
        """Directory for metadata generated by preprocessing runs."""
        path = self.get_trial_path() / "metadata"
        return path

    def get_trial_metadata_path(self) -> Path:
        """Alias for the trial-level metadata directory."""
        return self.get_metadata_path()

    def get_metadata_params_path(self) -> Path:
        """Path to the parameters JSON metadata file."""
        return self.get_metadata_path() / "params.json"

    def get_trial_metadata_params_path(self) -> Path:
        """Alias for the trial-level parameters JSON metadata file."""
        return self.get_metadata_params_path()

    def get_metadata_metrics_path(self) -> Path:
        """Path to the metrics JSON metadata file."""
        return self.get_metadata_path() / "metrics.json"

    def get_trial_metadata_metrics_path(self) -> Path:
        """Alias for the trial-level metrics JSON metadata file."""
        return self.get_metadata_metrics_path()

    def get_metadata_shape_path(self) -> Path:
        """Path to the shape CSV metadata file."""
        return self.get_metadata_path() / "shape.csv"

    def get_trial_metadata_shape_path(self) -> Path:
        """Alias for the trial-level shape CSV metadata file."""
        return self.get_metadata_shape_path()

    def get_feature_path(self) -> Path:
        """Directory for storing extracted feature files (joblib + baseline)."""
        path = self.root_path / "feature"
        return path

    def to_params(self) -> dict[str, Any]:
        """Serialize the option metadata into a JSON-friendly dictionary."""
        return {
            "name": self.name,
            "root_path": str(self.root_path),
            "subject_path": str(self.get_subject_path()),
            "subject_metadata_path": str(self.get_subject_metadata_path()),
            "subject_metadata_params_path": str(
                self.get_subject_metadata_params_path()
            ),
            "subject_metadata_metrics_path": str(
                self.get_subject_metadata_metrics_path()
            ),
            "subject_metadata_shape_path": str(self.get_subject_metadata_shape_path()),
            "trial_path": str(self.get_trial_path()),
            "trial_metadata_path": str(self.get_trial_metadata_path()),
            "trial_metadata_params_path": str(self.get_trial_metadata_params_path()),
            "trial_metadata_metrics_path": str(self.get_trial_metadata_metrics_path()),
            "trial_metadata_shape_path": str(self.get_trial_metadata_shape_path()),
            "metadata_path": str(self.get_metadata_path()),
            "metadata_params_path": str(self.get_metadata_params_path()),
            "metadata_metrics_path": str(self.get_metadata_metrics_path()),
            "metadata_shape_path": str(self.get_metadata_shape_path()),
            "feature_path": str(self.get_feature_path()),
        }
